service: blog-post
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  # blogs functions

  getAllBlogs:
    handler: src/handler.getAll
    timeout: 60
    memorySize: 128

  createBlog:
    handler: src/handler.create
    timeout: 60
    memorySize: 128
    events:
      - httpApi:
          path: /blogs/create
          method: post

  updateBlog:
    handler: src/handler.update
    timeout: 60
    memorySize: 128
    events:
      - httpApi:
          path: /blogs/update
          method: put

  deleteBlog:
    handler: src/handler.delete
    timeout: 60
    memorySize: 128
    events:
      - httpApi:
          path: /blogs/delete
          method: delete
